In [1]:
table_from_parquet_file = spark.sql("""
select distinct
first(UpdateID) as UpdateID,
first(AvailableQuantity) as AvailableQuantity,
first(AvailableQuantityActual) as AvailableQuantityActual,
SKU,
StoreId,
max(offset) as offset
from 
source_tables_rt.table_from_parquet_file
group by sku, storeid 
""") 
table_from_parquet_file.createOrReplaceTempView("table_from_parquet_file")

In [2]:
%sql
MERGE INTO source_tables_rt.stock as main
USING table_from_parquet_file as new
ON main.SKU = new.SKU AND main.storeId = new.storeId
WHEN MATCHED 
  THEN UPDATE SET main.UpdateID = new.UpdateID, main.AvailableQuantity = new.AvailableQuantity, main.offSet = new.offSet 
WHEN NOT MATCHED
  THEN INSERT (main.UpdateID, main.AvailableQuantity,main.SKU,main.StoreId,main.offset) VALUES (new.UpdateID, new.AvailableQuantity,new.SKU,new.StoreId,new.offset)

In [3]:
# %sql
# select * from source_tables_rt.stock where sku = '169248' -- and storeid in ('099','298','098')

UpdateID,AvailableQuantity,InventoryStatus,SKU,StoreId,ingestion_date,offset
null,1,,169248,046,2020-10-06T02:32:01.623+0000,-1
1233170727,0,,169248,087,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
null,1,,169248,089,2020-10-06T02:32:01.623+0000,-1
null,0,,169248,062,2020-10-06T02:32:01.623+0000,-1
1233282031,0,,169248,043,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
null,1,,169248,031,2020-10-06T02:32:01.623+0000,-1
null,1,,169248,063,2020-10-06T02:32:01.623+0000,-1
1233397255,0,,169248,052,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
null,1,,169248,605,2020-10-06T02:32:01.623+0000,-1
null,0,,169248,152,2020-10-06T02:32:01.623+0000,-1
1233328205,0,,169248,230,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
1233264254,0,,169248,057,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
1233431370,0,,169248,040,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
1233195733,1,,169248,685,2020-10-06T02:32:01.623+0000,2020-10-06 12:45:22.878959
null,0,,169248,099,2020-10-06T02:32:01.623+0000,-1